### ISSUE TITLE
Povezava z bazo

### ISSUE THREAD

**Issue by jonagricar** [jonagricar/Krvna-banka#2]
Še en problem, ki ga imava je ta, da jaz nimam dostopa do baze sem2019_katjam oziroma si ustvarjenih tabel na bazi ne morem pogledati. Imam lastno datoteko auth.R, v datoteki projekt.R pa sva tudi uredili dostope. V čem bi lahko bila težava?

**Comment by jernejbanevec** [comment]
Pogledal sem stavke in se mi zdijo v redu napisani. Ste https://github.com/jonagricar/Krvna-banka/blob/6b76c640d876c8db30e249120af44e055f97e06b/projekt.R#L168 pognali iz računalnika, v katerem so v _auth.R_ shranjeni podatki od tiste, na čigar bazi delate (v tem primeru mislim, da je to Katja, saj če prav vidim imate plan projekt narediti na njeni bazi)?

**Comment by katjamarina** [comment]
Našli sva napako, tako da sedaj dela, hvala!
